### register
POST http://localhost:3000/api/v1/auth/users/register
Content-Type: application/json

{
    "name":"mina",
    "email":"mina@mail.com",
    "password":"password123",
    "password_confirmation":"password123",
    "profile": {
    "identity_type": "KTP",
    "identity_number": 1234567890,
    "address": "Jl. satu no. 2"
  }
}


### login
POST http://localhost:3000/api/v1/auth/users/login
Content-Type: application/json

{
    "email":"sana@mail.com",
    "password":"password123"
}


### whoami
GET http://localhost:3000/api/v1/auth/users/whoami
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNjk3ODcwMjQ5fQ.zOIPE41DadEoPQ4FwTP125gEpgGNuJGjy0lX1eQaN1A

### authenticate User
GET http://localhost:3000/api/v1/auth/users/authenticate
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjk3Nzg5NDk0fQ.KxYZC-o4g7pb4PQ7VQr1hKJCNW4M_NdZ09Ce_p-GQ_I


### USERS
### all users with pagination
GET http://localhost:3000/api/v1/auth/users/pagination?limit=5&page=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4

### all users
GET http://localhost:3000/api/v1/auth/users/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4

### users detail by id
GET http://localhost:3000/api/v1/auth/users/detail/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4

### Update users by id
PUT http://localhost:3000/api/v1/auth/users/update/6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4

{
  "name": "Mina",
  "email": "mina@mail.com",
  "password": "minaUpdate",
  "profile": {
    "identity_type": "KTP",
    "identity_number": 123456789,
    "address": "Jl. satu no. 2"
  }
}

### delete users
DELETE http://localhost:3000/api/v1/auth/users/delete/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4

### ACCOUNTS
### create accounts
POST http://localhost:3000/api/v1/auth/accounts/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4
Content-Type: application/json

{
    "user_id": 8,
    "bank_name": "BCA",
    "bank_account_number": 987654320,
    "balance": 50000
}

### accounts with pagination
GET http://localhost:3000/api/v1/auth/accounts/pagination?limit=5&page=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4

### all accounts
GET http://localhost:3000/api/v1/auth/accounts/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4

### detail accounts by id
GET http://localhost:3000/api/v1/auth/accounts/detail/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4

### update account
PUT http://localhost:3000/api/v1/auth/accounts/update/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4
Content-Type: application/json

{
    "user_id": 6,
    "bank_name": "BCA",
    "bank_account_number": 987654321,
    "balance": 100000
}

### delete account
DELETE http://localhost:3000/api/v1/auth/accounts/delete/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4


### TRANSACTIONS
### Create Transactions
POST http://localhost:3000/api/v1/auth/transactions/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4
Content-Type: application/json

{
  "source_account_id": 2,
  "destination_account_id": 3,
  "amount": 10000
}

### data by paginations
GET http://localhost:3000/api/v1/auth/transactions/pagination?limit=2&page=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4

### all transactions
GET http://localhost:3000/api/v1/auth/transactions/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4

### detail transactions by id
GET http://localhost:3000/api/v1/auth/transactions/detail/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk3NzgxMzA0fQ.11bmOuaiapK9tF6mRnNqXoRtt9nNSahRft5Zn2uwZN4